---
- name: Installing dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - ptunnel
    - iodine

- name: Copy systemd ptunnel service
  copy:
    src: ptunnel.service
    dest: /etc/systemd/system/ptunnel.service
    mode: 0600

- name: Replace /etc/default/ptunnel
  template:
    src: ptunnel
    dest: /etc/default/ptunnel
    mode: 0600

- name: Copy systemd iodine service
  template:
    src: iodine.service
    dest: /etc/systemd/system/iodine.service
    mode: 0600

- name: Remove the packaged iodine service
  file:
    path: /lib/systemd/system/iodined.service
    state: absent

- name: reload systemd
  command: systemctl daemon-reload

- name: Start and enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - ptunnel
    - iodine